[package]
name = "rstr_projfs"
version = "0.2.0"
edition = "2024"

[lib]
name="rstr_projfs"
path="src/lib.rs"

[dependencies]
rstr_core = {path="../rstr_core"}
tokio = { version = "1.45.1", features = ["io-util", "rt", "sync"]}
windows-projfs = "0.1.7"
bytes = "1.10.1"